import { Link } from 'react-router-dom'
import ThemeToggle from './ThemeToggle'

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-bg-0 text-text-100 flex flex-col">
      <header className="flex items-center justify-between px-6 py-4 border-b border-bg-200">
        <Link to="/" className="flex items-center gap-3">
          <img src="/ana-logo.png" alt="Ana Logo" className="w-10 h-10 rounded-full object-cover" />
          <span className="text-xl font-normal tracking-wide" style={{ fontFamily: 'Alphacorsa, sans-serif' }}>Ana Solar</span>
        </Link>
        <div className="flex items-center gap-3">
          <ThemeToggle />
          <Link to="/chat" className="text-sm text-text-200 hover:text-text-100 border border-bg-200 px-4 py-2 rounded-lg transition-colors">
            Go to Chat
          </Link>
        </div>
      </header>

      <main className="flex-1 max-w-3xl mx-auto px-6 py-16">
        <h1 className="text-4xl font-medium text-text-100 mb-2">Terms of Service</h1>
        <p className="text-sm text-text-400 mb-8">Last updated: June 2026</p>

        <section className="space-y-6 text-[15px] leading-relaxed text-text-200">
          <h2 className="text-xl font-medium text-text-100 mt-8 mb-4">1. Acceptance of Terms</h2>
          <p>
            By accessing or using Ana GPA ("the Service"), you agree to be bound by these
            Terms of Service. If you do not agree, please do not use the Service.
          </p>

          <h2 className="text-xl font-medium text-text-100 mt-8 mb-4">2. Description of Service</h2>
          <p>
            Ana is an AI-powered personal assistant that provides text chat, voice interaction,
            image analysis, document generation, and device control features. The Service
            is provided "as is" and may be updated or modified at any time.
          </p>

          <h2 className="text-xl font-medium text-text-100 mt-8 mb-4">3. User Responsibilities</h2>
          <ul className="list-disc pl-6 space-y-2">
            <li>You are responsible for maintaining the confidentiality of your account credentials.</li>
            <li>You agree not to use the Service for any unlawful purpose or in violation of any applicable laws.</li>
            <li>You agree not to attempt to reverse engineer, hack, or disrupt the Service.</li>
            <li>You are responsible for all content you submit through the Service.</li>
          </ul>

          <h2 className="text-xl font-medium text-text-100 mt-8 mb-4">4. AI-Generated Content</h2>
          <p>
            Ana's responses are generated by AI models and may contain errors, inaccuracies,
            or unexpected content. You should independently verify important information.
            DTC Team is not liable for any damages arising from reliance on AI-generated content.
          </p>

          <h2 className="text-xl font-medium text-text-100 mt-8 mb-4">5. Privacy</h2>
          <p>
            Your use of the Service is governed by our Privacy Policy, which is incorporated
            into these terms by reference.
          </p>

          <h2 className="text-xl font-medium text-text-100 mt-8 mb-4">6. Limitation of Liability</h2>
          <p>
            DTC Team shall not be liable for any indirect, incidental, special, consequential,
            or punitive damages arising from your use of the Service. The Service is provided
            without warranty of any kind, express or implied.
          </p>

          <h2 className="text-xl font-medium text-text-100 mt-8 mb-4">7. Termination</h2>
          <p>
            We reserve the right to suspend or terminate access to the Service at any time,
            without notice, for conduct that we believe violates these terms or is harmful
            to other users, third parties, or the Service itself.
          </p>

          <h2 className="text-xl font-medium text-text-100 mt-8 mb-4">8. Changes to Terms</h2>
          <p>
            We may modify these terms at any time. Continued use of the Service after
            changes constitutes acceptance of the new terms. We will notify users of
            material changes via email or in-app notification.
          </p>

          <h2 className="text-xl font-medium text-text-100 mt-8 mb-4">9. Contact</h2>
          <p>
            For questions about these terms, contact us at{' '}
            <a href="mailto:legal@anagpa.com" className="text-text-200 hover:text-text-100 underline">
              legal@anagpa.com
            </a>.
          </p>
        </section>
      </main>

      <footer className="border-t border-bg-200 py-6 text-center text-sm text-text-400">
        &copy; {new Date().getFullYear()} DTC Team — Ana GPA
      </footer>
    </div>
  )
}
